Repository yoonhee-nam/TeamNo.7, pull requests merged in 2023-08, with the labels that each got.

#12 [FEAT] : ⚙️ Activity간 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/team77/DetailActivity.kt
  app/src/main/java/com/example/team77/MainActivity.kt
  app/src/main/java/com/example/team77/MyPageActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_signup.xml
Labels: feature

#14 Main page feature
  app/src/main/java/com/example/team77/MainActivity.kt
  app/src/main/java/com/example/team77/MyPageActivity.kt
  app/src/main/res/drawable/like.xml
  app/src/main/res/drawable/main_bg_white.xml
  app/src/main/res/layout/activity_main.xml
Labels: feature

#17 Login page feature
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/team77/LogInActivity.kt
  app/src/main/java/com/example/team77/MyPageActivity.kt
  app/src/main/java/com/example/team77/PasswordActivity.kt
  app/src/main/java/com/example/team77/SignUpActivity.kt
  app/src/main/java/com/example/team77/member/DB.kt
  app/src/main/java/com/example/team77/member/Member.kt
  app/src/main/java/com/example/team77/member/SearchActivity.kt
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_search.xml
Labels: UI, feature

#18 [DESIGN] : 🎨 회원정보관리 버튼,UI(약간)수정
  .idea/misc.xml
  app/src/main/java/com/example/team77/MyPageActivity.kt
  app/src/main/java/com/example/team77/member/SearchActivity.kt
  app/src/main/res/drawable/cog_wheel.png
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_search.xml
Labels: UI

#19 Moving animation
  app/src/main/java/com/example/team77/DetailActivity.kt
  app/src/main/java/com/example/team77/DoneActivity.kt
  app/src/main/java/com/example/team77/LogInActivity.kt
  app/src/main/java/com/example/team77/MainActivity.kt
  app/src/main/java/com/example/team77/MyPageActivity.kt
  app/src/main/java/com/example/team77/PasswordActivity.kt
  app/src/main/java/com/example/team77/SignUpActivity.kt
  app/src/main/java/com/example/team77/member/SearchActivity.kt
  app/src/main/res/anim/down_fade_out.xml
  app/src/main/res/anim/down_faid_in.xml
  app/src/main/res/anim/left_fade_in.xml
  app/src/main/res/anim/left_fade_out.xml
  app/src/main/res/anim/right_fade_in.xml
  app/src/main/res/anim/right_fade_out.xml
  app/src/main/res/anim/up_fade_in.xml
  app/src/main/res/anim/up_fade_out.xml
  app/src/main/res/layout/activity_main.xml
Labels: feature

#20 [DESIGN] : 🎨
  app/src/main/java/com/example/team77/DetailActivity.kt
  app/src/main/java/com/example/team77/DoneActivity.kt
  app/src/main/java/com/example/team77/LogInActivity.kt
  app/src/main/java/com/example/team77/MainActivity.kt
  app/src/main/java/com/example/team77/MyPageActivity.kt
  app/src/main/java/com/example/team77/PasswordActivity.kt
  app/src/main/java/com/example/team77/SignUpActivity.kt
  app/src/main/res/drawable/main_bg_color.xml
  app/src/main/res/drawable/main_bg_white.xml
  app/src/main/res/drawable/minicap.png
  app/src/main/res/drawable/run_gif.gif
  app/src/main/res/layout/activity_done.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/toast_layout.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: UI, feature
